// nav.constants.ts
import { ROUTES } from '../../core/constants/route.constants';

/** @deprecated Use ROUTES from core/constants/route.constants.ts */
export const APP_ROUTE_PATHS = {
  dashboard: ROUTES.dashboard,
  users: ROUTES.users.base,
  roles: ROUTES.roles.base,
  permissions: ROUTES.permissions.base,
  customers: ROUTES.customers.base,
  products: ROUTES.products.base,
  inventory: ROUTES.inventory.base,
  suppliers: ROUTES.suppliers.base,
  purchaseOrders: ROUTES.purchaseOrders.base,
  orders: ROUTES.orders.base,
  quotations: ROUTES.quotations.base,
  invoices: ROUTES.invoices.base,
  payments: ROUTES.payments.base,
  sales: ROUTES.sales.base,
  reports: ROUTES.reports,
  expenses: ROUTES.expenses.base,
  expenseCategories: ROUTES.expenseCategories.base,
  finance: ROUTES.finance.base,
  audit: ROUTES.audit.base,
  notifications: ROUTES.notifications.base,
  settings: ROUTES.settings.base,
  admin: ROUTES.admin.base,
  profile: ROUTES.profile,
  onboarding: ROUTES.onboarding.base,
  forbidden: ROUTES.forbidden,
  notFound: ROUTES.notFound,
} as const;

export { ROUTES };

export interface NavItem {
  label: string;
  icon: string;
  route: string;
  description: string;
  permissions?: string[];
  group?: 'Finance' | 'Administration';
}

/** Compact quick links shown in the top navbar (sidebar holds full navigation). */
export const TOP_NAV_ITEMS: NavItem[] = [
  {
    label: 'Sales Dashboard',
    icon: 'fa-chart-line',
    route: ROUTES.sales.dashboard,
    description: 'Sales KPIs, revenue trends, and top products.',
    permissions: ['Order.View'],
  },
  {
    label: 'Reports',
    icon: 'fa-chart-bar',
    route: ROUTES.reports,
    description: 'Analyze business performance and trends.',
    permissions: ['Report.View'],
  },
  {
    label: 'Financial Dashboard',
    icon: 'fa-coins',
    route: ROUTES.finance.dashboard,
    description: 'Financial KPIs, revenue and expense trends.',
    permissions: ['Finance.View'],
  },
];

export const NAV_ITEMS: NavItem[] = [
  {
    label: 'Dashboard',
    icon: 'fa-chart-pie',
    route: ROUTES.dashboard,
    description: 'Overview of sales, orders, inventory, and key metrics.',
  },
  {
    label: 'Products',
    icon: 'fa-cube',
    route: ROUTES.products.base,
    description: 'Manage product catalog and pricing.',
    permissions: ['Product.View'],
  },
  {
    label: 'Inventory',
    icon: 'fa-warehouse',
    route: ROUTES.inventory.base,
    description: 'Track stock levels and inventory movements.',
    permissions: ['Inventory.View'],
  },
  {
    label: 'Suppliers',
    icon: 'fa-truck',
    route: ROUTES.suppliers.base,
    description: 'Manage supplier contacts and purchase relationships.',
    permissions: ['Supplier.View'],
  },
  {
    label: 'Purchase Orders',
    icon: 'fa-clipboard-list',
    route: ROUTES.purchaseOrders.base,
    description: 'Create and track purchase orders from suppliers.',
    permissions: ['PurchaseOrder.View'],
  },
  {
    label: 'Customers',
    icon: 'fa-user-tie',
    route: ROUTES.customers.base,
    description: 'Manage customer records and relationships.',
    permissions: ['Customer.View'],
  },
  {
    label: 'Orders',
    icon: 'fa-shopping-cart',
    route: ROUTES.orders.base,
    description: 'View and manage customer orders.',
    permissions: ['Order.View'],
  },
  {
    label: 'Quotations',
    icon: 'fa-file-signature',
    route: ROUTES.quotations.base,
    description: 'Create and track customer quotations.',
    permissions: ['Quotation.View'],
  },
  {
    label: 'Invoices',
    icon: 'fa-file-invoice',
    route: ROUTES.invoices.base,
    description: 'Review billing and invoice history.',
    permissions: ['Invoice.View'],
  },
  {
    label: 'Payments',
    icon: 'fa-credit-card',
    route: ROUTES.payments.base,
    description: 'Record and track customer payments.',
    permissions: ['Payment.View'],
  },
  {
    label: 'Sales Dashboard',
    icon: 'fa-chart-line',
    route: ROUTES.sales.dashboard,
    description: 'Sales KPIs, revenue trends, and top products.',
    permissions: ['Order.View'],
  },
  {
    label: 'Reports',
    icon: 'fa-chart-bar',
    route: ROUTES.reports,
    description: 'Analyze business performance and trends.',
    permissions: ['Report.View'],
  },
  {
    label: 'Business Analytics',
    icon: 'fa-chart-area',
    route: ROUTES.analytics.base,
    description: 'Advanced analytics across customers, projects, revenue, and expenses.',
    permissions: ['Analytics.View'],
  },
  {
    label: 'Financial Dashboard',
    icon: 'fa-coins',
    route: ROUTES.finance.dashboard,
    description: 'Financial KPIs, revenue and expense trends.',
    permissions: ['Finance.View'],
    group: 'Finance',
  },
  {
    label: 'Expenses',
    icon: 'fa-arrow-up-right-dots',
    route: ROUTES.expenses.base,
    description: 'Track and manage business expenses.',
    permissions: ['Expense.View'],
    group: 'Finance',
  },
  {
    label: 'Expense Categories',
    icon: 'fa-tags',
    route: ROUTES.expenseCategories.base,
    description: 'Organize expenses into categories.',
    permissions: ['ExpenseCategory.View'],
    group: 'Finance',
  },
  {
    label: 'Profit & Loss',
    icon: 'fa-bullseye',
    route: ROUTES.finance.profitLoss,
    description: 'Analyze revenue, expenses, and profitability.',
    permissions: ['Finance.View'],
    group: 'Finance',
  },
  {
    label: 'Team',
    icon: 'fa-users',
    route: ROUTES.team.base,
    description: 'Manage team members, roles, and collaboration.',
    permissions: ['Team.View'],
    group: 'Administration',
  },
  {
    label: 'Tenant',
    icon: 'fa-building',
    route: ROUTES.tenant.dashboard,
    description: 'Tenant dashboard, plan, and resource usage.',
    permissions: ['Tenant.View'],
    group: 'Administration',
  },
  {
    label: 'Organization',
    icon: 'fa-city',
    route: ROUTES.organization.base,
    description: 'Organization profile, logo, timezone, and currency.',
    permissions: ['Organization.View'],
    group: 'Administration',
  },
  {
    label: 'Users',
    icon: 'fa-user-group',
    route: ROUTES.users.base,
    description: 'Manage user accounts and access.',
    permissions: ['User.View'],
    group: 'Administration',
  },
  {
    label: 'Roles',
    icon: 'fa-shield-halved',
    route: ROUTES.roles.base,
    description: 'Configure roles and assign permissions.',
    permissions: ['Role.View'],
    group: 'Administration',
  },
  {
    label: 'Permissions',
    icon: 'fa-key',
    route: ROUTES.permissions.base,
    description: 'Review permission definitions across the system.',
    permissions: ['Role.View'],
    group: 'Administration',
  },
  {
    label: 'Audit Logs',
    icon: 'fa-clipboard',
    route: ROUTES.audit.base,
    description: 'Review system audit trail and entity changes.',
    permissions: ['Audit.View'],
    group: 'Administration',
  },
  {
    label: 'Activity',
    icon: 'fa-clock',
    route: ROUTES.activity.base,
    description: 'View business activity timeline.',
    permissions: ['Activity.View'],
    group: 'Administration',
  },
  {
    label: 'Notifications',
    icon: 'fa-bell',
    route: ROUTES.notifications.base,
    description: 'View and manage notifications.',
    permissions: ['Notification.View'],
    group: 'Administration',
  },
  {
    label: 'Billing',
    icon: 'fa-receipt',
    route: ROUTES.billing.base,
    description: 'Manage subscription, usage, and invoices.',
    permissions: ['Subscription.View'],
    group: 'Administration',
  },
  {
    label: 'Pricing',
    icon: 'fa-tag',
    route: ROUTES.pricing.base,
    description: 'Compare plans and upgrade your subscription.',
    permissions: ['Subscription.View'],
    group: 'Administration',
  },
  {
    label: 'Settings',
    icon: 'fa-gear',
    route: ROUTES.settings.base,
    description: 'Configure application and tenant settings.',
    permissions: ['Settings.View'],
    group: 'Administration',
  },
  {
    label: 'System Admin',
    icon: 'fa-server',
    route: ROUTES.admin.base,
    description: 'Monitor system health, stats, and environment.',
    permissions: ['SystemAdmin.View'],
    group: 'Administration',
  },
];