/** Canonical CSS custom property names used across the design system */
export const THEME_CSS_TOKENS = {
  primary: '--primary-color',
  primaryHover: '--primary-hover-color',
  primaryLight: '--primary-light-color',
  secondary: '--secondary-color',
  background: '--background-color',
  surface: '--surface-color',
  text: '--text-color',
  textMuted: '--text-muted-color',
  border: '--border-color',
  success: '--success-color',
  successLight: '--success-light-color',
  danger: '--danger-color',
  dangerLight: '--danger-light-color',
  warning: '--warning-color',
  warningLight: '--warning-light-color',
  info: '--info-color',
  infoLight: '--info-light-color',
  shadow: '--shadow-color',
  sidebarBackground: '--sidebar-background',
  sidebarText: '--sidebar-text-color',
  sidebarActive: '--sidebar-active-color',
  navbarBackground: '--navbar-background',
  tableHeaderBackground: '--table-header-background',
  chartPrimary: '--chart-primary-color',
  overlayBackdrop: '--overlay-backdrop-color',
  textOnPrimary: '--text-on-primary-color',
} as const;

/** Legacy token aliases mapped to new canonical names for backward compatibility */
export const LEGACY_TOKEN_ALIASES: Record<string, string> = {
  '--color-primary': '--primary-color',
  '--color-primary-hover': '--primary-hover-color',
  '--color-primary-light': '--primary-light-color',
  '--color-bg': '--background-color',
  '--color-surface': '--surface-color',
  '--color-text': '--text-color',
  '--color-text-muted': '--text-muted-color',
  '--color-border': '--border-color',
  '--color-success': '--success-color',
  '--color-success-light': '--success-light-color',
  '--color-danger': '--danger-color',
  '--color-danger-light': '--danger-light-color',
  '--color-warning': '--warning-color',
  '--color-warning-light': '--warning-light-color',
  '--color-info': '--info-color',
  '--color-info-light': '--info-light-color',
  '--color-sidebar-bg': '--sidebar-background',
  '--color-sidebar-text': '--sidebar-text-color',
  '--color-sidebar-active': '--sidebar-active-color',
};

export type ThemeCssToken = (typeof THEME_CSS_TOKENS)[keyof typeof THEME_CSS_TOKENS];
